--- 
title: "Jekyllマニュアル"
author: "Sophia-kurata-seminar"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "上智大学倉田ゼミのHPで使用している、Jekyllの使用方法についてまとめたサイトです。"
---

#  事前準備{-}

## Ruby,Jekyllのインストール  

以下のサイトを参考に、インストールを進めてください。注意事項や重要事項だけ、以下にまとめたので、併せて確認してみて下さい。

参考：<http://jekyllrb-ja.github.io/docs/installation/windows/>

<b>RubyInstallerをインストールする</b>  

RubyInstallerのサイトから、Rubyインストーラーをインストールする際には、【WITH DEVKIT】の中で、太字になっているバージョンをダウンロードすることをお勧めします。

<b>JekyllとBundlerをインストールする</b>  

コマンドプロンプトを開き、
```
gem install jekyll bundler
```
を入力すると、JekyllとBundlerがインストールされます。

以下のコマンドで、インストールできているか確認してみましょう。
```
jekyll -v
```

## 基礎知識

ここまでインストールの仕方を説明してきましたが、ここからは用語の説明です。  
参考：<https://qiita.com/oshou/items/6283c2315dc7dd244aef>

<b>Ruby,jekyllとは</b>  

Rubyはプログラミング言語のひとつで、jekyllはこの言語で書かれています。jekyllとは、Rubyで書かれた（静的）サイトを作るソフトウェアのことで、テンプレートを使えば簡単にサイトを作成できます。

jekyllテンプレートのサイト：<https://jekyllthemes.io/github-pages-themes>

<b>Gemとは</b>  

Gemとは、Rでいうパッケージのことです。プログラム言語は機能をまとめたライブラリーというものを作成していることが多くあり、RubyではライブラリーのことをGemと呼びます。使いたいgemをgemfileに記入すればそのgemの機能を簡単に使うことができます。

<b>bundlerとは</b>  

Gem同士の依存関係を整理するものです。bundler自体もgemのひとつですが、以下のような場合に備えて使用します。  

GemAを使うために、GemBを使う。さらにGemBを使うためにはGemCを使う時、GemCがアップデートされるとAもBも使えなくなる場合がある。こういう場合に、bundlerはgem同士の互換性を保ちながら各gemの導入、管理を行ってくれます。  

特に、共同作業を行う場合、自分と相手のGemのバージョンが異なると、エラーメッセージが表示されます。なので、定期的に以下のコマンドで、Gemの管理を行いましょう。
```
bundle install
bundle update
```
